sampling:
  order: 250
  method: halton

uncertainties:
    onwind:
      type: Uniform
      args: [0.5,1.5]
    offwind:
      type: Uniform
      args: [0.5,1.5]
    solar:
      type: Uniform
      args: [0.5,1.5]
    H2:
      type: Uniform
      args: [0.5,1.5]
    battery:
      type: Uniform
      args: [0.5,1.5]
