scenarios:
  low:
    clusters: 37
    opts: 4H
  high:
    clusters: 128
    opts: 2H

nearoptimal:
  epsilon: [0.01, 0.02, 0.04, 0.08] # skips nearoptimal if empty
  objective:
    #- Generator+offwind+min
    #- Generator+offwind+max
    #- Generator+onwind+min
    #- Generator+onwind+max
    - Generator+wind+min
    - Generator+wind+max
    - Generator+solar+min
    - Generator+solar+max
    - StorageUnit+H2+min
    - StorageUnit+H2+max
    - StorageUnit+battery+min
    - StorageUnit+battery+max
    - Transmission++min
    - Transmission++max

experimental_design:
  low:
    size: 300
    rule: halton
    round: 3
  high:
    size: 10
    rule: halton
    round: 3

uncertainties:
    onwind:
      type: Uniform
      args: [0.670,1]
    offwind:
      type: Uniform
      args: [0.726,1]
    solar:
      type: Uniform
      args: [0.679,1]
    H2:
      type: Uniform
      args: [0.429,1]
    battery:
      type: Uniform
      args: [0.240,1]

enable:
  collect_samples: false

surrogate:
  cost:
    order: 3
    correction:
      approach: "additive"
      order: 2
  epsilon:
    order: 5
    correction:
      approach: "additive"
      order: 3

lines:
  s_nom_add: 8000
  s_nom_factor: 2

links:
  p_nom_max: 20000

solving:
  options:
    formulation: kirchhoff
    load_shedding: false
    noisy_costs: true
    clip_p_max_pu: 0.01
    skip_iterations: true
  solver:
    name: gurobi
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-3
    FeasibilityTol: 1.e-3
    AggFill: 0
    PreDual: 0
    GURO_PAR_BARDENSETHRESH: 200
    BarHomogeneous: 1
    #NumericFocus: 2 # for numeric
    #Presolve: 0 # for numeric
    #Aggregate: 0 # for numeric

train_test_split:
  train_size: 0.8
  shuffle: true

# with_sklearn:
#   method: Lars
#   fit_intercept: false

csvargs:
  float_format: "%.4f"
