sampling:
  order: 250
  method: halton
  space: uniform-50pc

uncertainty:
  uniform-50pc:  # some name
    onwind:
      distribution: Uniform
      params: [0.5,1.5]
    offwind:
      distribution: Uniform
      params: [0.5,1.5]
    solar:
      distribution: Uniform
      params: [0.5,1.5]
    H2:
      distribution: Uniform
      params: [0.5,1.5]
    battery:
      distribution: Uniform
      params: [0.5,1.5]
  uniform-25pc:
    onwind:
      distribution: Uniform
      params: [0.75,1.25]
    offwind:
      distribution: Uniform
      params: [0.75,1.25]
    solar:
      distribution: Uniform
      params: [0.75,1.25]
    H2:
      distribution: Uniform
      params: [0.75,1.25]
    battery:
      distribution: Uniform
      params: [0.75,1.25]
