scenarios:
  clusters: [37]
  opts: [168H]
  epsilon: [0.01] # skips nearoptimal if empty
  objective:
    - Generator+offwind+min
    #- Generator+offwind+max
    - Generator+onwind+min
    #- Generator+onwind+max
    - Generator+wind+min
    #- Generator+wind+max
    - Generator+solar+min
    #- Generator+solar+max
    - StorageUnit+H2+min
    #- StorageUnit+H2+max
    - StorageUnit+battery+min
    #- StorageUnit+battery+max
    - StorageUnit++min
    #- StorageUnit++max
    - Transmission++min
    #- Transmission++max
  order: [1,2,3,4,5]
  sobol: [t, m]

enable:
  collect_samples: true

nearoptimal:
  with_fix: true

solving:
  options:
    formulation: kirchhoff
    load_shedding: false
    noisy_costs: true
    clip_p_max_pu: 0.01
    skip_iterations: true
  solver:
    name: gurobi
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-4
    FeasibilityTol: 1.e-4
    AggFill: 0
    PreDual: 0
    GURO_PAR_BARDENSETHRESH: 200

experimental_design:
  size: 5
  rule: halton
  round: 3

uncertainties:
    onwind:
      type: Uniform
      args: [0.2,1.5]
    offwind:
      type: Uniform
      args: [0.2,1.5]
    solar:
      type: Uniform
      args: [0.2,1.5]
    H2:
      type: Uniform
      args: [0.2,1.5]
    battery:
      type: Uniform
      args: [0.2,1.5]

train_test_split:
  train_size: 0.8
  shuffle: true

neural_network:
  solver: adam
  hidden_layer_sizes: [50,]
  max_iter: 100000
  early_stopping: false
  tol: 1.e-4
  n_iter_no_change: 10

with_sklearn:
  method: Lars
  fit_intercept: false

csvargs:
  float_format: "%.4f"
