version: 0.1.0

# considered years for output data
years : [2050]

expectation : "pessimist" # tech data uncertainty, possible options [None, "optimist", "pessimist"]

rate_inflation : 0.02

#year for EUR outputs
#NB: 2015 is standard year in DEA, and DEA is NOT yet adjusted
#if this is changed, only non-DEA
eur_year : 2015

# add solar from different source
solar_utility_from_vartiaien : false
solar_rooftop_from_etip : true

# add fuel cell/electrolysis efficiencies from Budischak (DEA assumptions very conservative)
h2_from_budischak : false

# remove grid connection costs from DEA for offwind because they are calculated
# seperately in pypsa-eur
offwind_no_gridcosts : true
